miguelgrinberg/Flask-SocketIO

- README.md
Updated example in README to move away from flask.ext imports as they will be deprecated in v1.0, see: https://github.com/mitsuhiko/flask/issues/1182
> Change README to reflect deprecated .ext import format

- flask_socketio/__init__.py
Currently `engineio.Server` throws an error when the `resource` keyword argument is provided because it is not one of the options. These changes fix the issue.
On a side note:
I spent a few minutes trying to write a test case for this but the module seems very fragile. Some of the issues I've noticed:
* `init_app()` style does not work. `SocketIO.on` decorator uses uninitialized values
* The line `if self.server is None: self.run(app)` in `SocketIO.test_client` doesn't make sense because the run method never initializes `self.server` causing various `NoneType` attribute errors
> Fix custom resource path.

- test_socketio.py
This means that the failure messages will be more useful - assertTrue(1 == 2) gives a message 'False is not true', whereas assertEqual(1, 2) gives the message '2 != 1'
> Replace assertTrue with assertEqual where possible.

- flask_socketio/__init__.py
This pull request fixes a minor issue with `emit()`, which used to require a request context even when the namespace argument was specified. This happens because `kwargs.get()` evaluates its second argument in an eager manner. The pull request fixes this by replacing `kwargs.get()` with a membership check, falling back to the namespace of the current request context only if the `namespace` keyword argument is not present.
> request context should not be needed when calling emit() with namespace

- flask_socketio/__init__.py
Fix “ithreading” to “threading”
> Fix typo in documentation

- example/templates/index.html
Previously just the http protocol was used.
The `io.connect` function now uses `location.protocol` (creds to Miguel).
This generalizes so that the socket connection can be
made for both http and https.
https://github.com/miguelgrinberg/Flask-SocketIO/issues/335
> Improve socketio connect function for http[s]

- docs/index.rst
Not having "self" in the instance methods for the custom namespace example was confusing.
> Update custom namespace doc example

- flask_socketio/__init__.py
this requires a corresponding change to python-socketio, for which I will file another pull request.
> add support for using zmq as the message queue transport

- flask_socketio/__init__.py
This is for issue: https://github.com/miguelgrinberg/Flask-SocketIO/issues/432
> specify namespace in room related functions

- flask_socketio/__init__.py
In this case, it works well:
> socketio = SockeIO(app, path='/path/socket.io')
While this case, it doesn't worked before the change:
> socketio = SockeIO(path='/path/socket.io')
> socketio.init_app(app)
So that this change can fix it.
> Fix 'path' or 'resource' doesn't work.

- flask_socketio/__init__.py
Eventlet forces an explicit protocol in listen(), and the default is AF_INET.
To successfully bind to '::' one has to specify AF_INET6, so this PR manages both cases.
> Added an optional IPv6 support in eventlet

- flask_socketio/__init__.py
The emit method currently does not allow to pass ignore_queue to a pubsub backend. 
this PR exposes the ignore_queue parameter to the user so he can decide not to emit through the backend but only locally on the current server.
> expose ignore_queue param in the emit method

- flask_socketio/__init__.py
there is any reason to not pass **kwarg pywsgi.WSGIServer in the case WebSocketHandler fail to import?
> added **kwarg to  pywsgi.WSGIServer when import WebSocketHandler failed

- flask_socketio/__init__.py
The `send()` function should pass the `json` argument to the basic `SocketIO.send()` method.
> Add missing json argument in send() function

- flask_socketio/cli.py
In [CS50](https://cs50.harvard.edu/) (Introduction to Computer Science) at Harvard we use `Flask` in the second half of the course. We have our own customized development environment (CS50 IDE) which is a cloud-based IDE based on [Cloud9](https://github.com/c9/core) that students are encouraged to use since it allows them to try any of the code demos if they want and start working on their assignments immediately without having to worry about setting up and configuring a local development environment. 
In this environment we provide students with a wrapper around the `flask` CLI to abstract some of the complexities away from them. At the end of the course, students decide on a final project as their graduation project and they're allowed to use any environment(s) and toolset(s) that …
> support --with(out)-threads for compatibility

- flask_socketio/test_client.py
- test_socketio.py
If you preinitialize all the test clients, you won't get the server
acknowledgements because only the last initialized test client's
monkeypatched successfully `_send_packet`, with `self` in its closure. So
when other test client instances check `self.ack is None` when
`callback=True` in `emit()`, it doesn't contain the ack meant for them.
Fixes #730
> Fix test client [call]back returning

- flask_socketio/test_client.py
- test_socketio.py
This PR makes possible to test disconnect event from server. Now, if servers closes the connection, corresponding `connected` state is set to `False` in test client.
> SocketIOTestClient can handle disconnect event from server

- setup.py
Hi Miguel, I've updated the minimum required version of python-socketio to 4.0.0 since that seems to be the least version which supports the ConnectionRefusedError exception.
Please, let me know if any corrections or improvements are necessary since this is my first PR.
> Flask-SocketIO 4.1.0 requires python-socketio 4.0.0 to support ConnectionRefusedError

- flask_socketio/__init__.py
Took me some time to figure out that I had to install a new dependency, since it wasn't being logged in this particular case.
> Log when gevent is used but WebSocket is missing

- flask_socketio/__init__.py
There is a small typo in flask_socketio/__init__.py.
Closes #1221
> docs: Fix simple typo, addresee -> addressee

- docs/index.rst
`handle_my_custom_event` function uses `emit` but it wasn't imported in the mini-example
> Added a missing import in the example

- flask_socketio/__init__.py
Fixed missing call to ``has_request_context`` in [this line](https://github.com/miguelgrinberg/Flask-SocketIO/blob/e937571a8d43fa604e3e348cedb477973503f510/flask_socketio/__init__.py#L411):
- Added proper call to ``has_request_context`` function
> Fixing issue #1324

- docs/index.rst
socketio.send and socketio.emit now take the to= argument instead of the room= argument.  Upgrade this part of the documentation to reflect changes in the program & in the later parts of the documentation.
> change room documentation from room= to to=

- docs/index.rst
The example for load balancing multiple Socket.IO servers had `locaton / static` instead of `location / static`
> Fix typo in example

- flask_socketio/__init__.py
Fixed typo in flask_socketio/__init__.py
> Fixed typos in documentation

- src/flask_socketio/__init__.py
Fix minor inconsistency in documentation regarding examples.
> changed send(room=) to send(to=) in examples

- docs/getting_started.rst
Changed `ConectionRefusedError` to `ConnectionRefusedError`
> Fix Typo in `getting_started.rst`

- src/flask_socketio/__init__.py
Running a (non-production) Flask-SocketIO app in an environment without a real shell requires to pass `allow_unsafe_werkzeug=True` into `socketio.run()`. However, adding this option results in an error when run with a real shell (e.g. for development purposes), as the option is passed to `app.run()` which then complains about it:
```
Traceback (most recent call last):
File "dev/app.py", line 48, in <module>
socketio.run(
File "dev/.venv/lib/python3.10/site-packages/flask_socketio/__init__.py", line 649, in run
app.run(host=host, port=port, threaded=True,
File "dev/.venv/lib/python3.10/site-packages/flask/app.py", line 1188, in run
run_simple(t.cast(str, host), port, self, **options)
TypeError: run_simple() got an unexpected keyword argument 'allow_unsafe_werkzeug'
```
There is a simple …
> Always pop `allow_unsafe_werkzeug` from kwargs

- src/flask_socketio/__init__.py
There are small typos in:
- src/flask_socketio/__init__.py
Fixes:
- Should read `middleware` rather than `middlware`.
- Should read `method` rather than `methond`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- docs/deployment.rst
The current Nginx example configuration in the docs is potentially vulnerable.
This PR fixes that to avoid people introducing potential issues in their apps when copy-pasting that configuration.
This is the current configuration:
```nginx
location /static {
alias <path-to-your-application>/static;
expires 30d;
}
```
in case there are two separate folders, `<path-to-your-application>/static` and `<path-to-your-application>/static_secret` this setup would allow an attacker to access all the files contained in `/static_secret` just by requesting `http://[domain]/static_secret/[file]`. Adding a final slash ensures only the `static` folder is served.
```nginx
location /static/ {
alias <path-to-your-application>/static/;
expires 30d;
}
```
Note that as we add the slash to `alias …
> More secure nginx configuration examples
